### ISSUE TITLE
customConfig

### ISSUE THREAD

**Issue by aprz512** [Yalfoosh/CustomConfig#1]
i want to build my own zoolock decklist, but dont kown how to write the json file.
where can i get the card id?

**Comment by Yalfoosh** [comment]
I think I have added a text file called All.txt in which I put most of the cards with their card ids. Generally what I do is I visit hearthstonejson and look at the API. I copy the API when an update comes and use Regex to separate the ID and card name from the other data I don't need.

**Comment by aprz512** [comment]
THANKS
